"""cascade institution deletion

Revision ID: 168c6ccd9e49
Revises: a1b2c3d4e5f6
Create Date: 2026-09-10 16:51:04.859950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168c6ccd9e49'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attendance_student_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'student_profiles', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('challenge_assignments_team_id_fkey'), 'challenge_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'challenge_assignments', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cohorts_institution_id_fkey'), 'cohorts', type_='foreignkey')
    op.create_foreign_key(None, 'cohorts', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('companies_slug_key'), 'companies', type_='unique')
    op.drop_constraint(op.f('enrollments_cohort_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'cohorts', ['cohort_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('mentors_user_id_key'), 'mentors', type_='unique')
    op.drop_constraint(op.f('sessions_cohort_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'cohorts', ['cohort_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_cohort_assignments_cohort_id_fkey'), 'student_cohort_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'student_cohort_assignments', 'cohorts', ['cohort_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_profiles_institution_id_fkey'), 'student_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'student_profiles', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('submissions_team_id_fkey'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_task_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'session_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('uq_student_single_active_team'), table_name='team_members', postgresql_where='(left_at IS NULL)')
    op.drop_constraint(op.f('team_members_student_id_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'student_profiles', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teams_cohort_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'cohorts', ['cohort_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_cohort_id_fkey'), 'teams', 'cohorts', ['cohort_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_student_id_fkey'), 'team_members', 'student_profiles', ['student_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('uq_student_single_active_team'), 'team_members', ['student_id'], unique=True, postgresql_where='(left_at IS NULL)')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_task_id_fkey'), 'submissions', 'session_tasks', ['task_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('submissions_team_id_fkey'), 'submissions', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('student_profiles_institution_id_fkey'), 'student_profiles', 'institutions', ['institution_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'student_cohort_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('student_cohort_assignments_cohort_id_fkey'), 'student_cohort_assignments', 'cohorts', ['cohort_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_cohort_id_fkey'), 'sessions', 'cohorts', ['cohort_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint(op.f('mentors_user_id_key'), 'mentors', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_cohort_id_fkey'), 'enrollments', 'cohorts', ['cohort_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint(op.f('companies_slug_key'), 'companies', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'cohorts', type_='foreignkey')
    op.create_foreign_key(op.f('cohorts_institution_id_fkey'), 'cohorts', 'institutions', ['institution_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'challenge_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('challenge_assignments_team_id_fkey'), 'challenge_assignments', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_student_id_fkey'), 'attendance', 'student_profiles', ['student_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
