"""restore active team uniqueness

Revision ID: e20b9dbb8e2c
Revises: 168c6ccd9e49
Create Date: 2026-09-10 16:57:14.766742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20b9dbb8e2c'
down_revision: Union[str, Sequence[str], None] = '168c6ccd9e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_student_single_active_team', 'team_members', ['student_id'], unique=True, postgresql_where=sa.text('left_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_student_single_active_team', table_name='team_members', postgresql_where=sa.text('left_at IS NULL'))
    # ### end Alembic commands ###
